name: Full DevSecOps Pipeline

on:
  push:
    branches: ["main"]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout
      - uses: actions/checkout@v4

      # ✅ Set Image Tag
      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # ✅ Node setup
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # ✅ Install deps
      - name: Install Dependencies
        run: |
          cd backend/user-service && npm install || true
          cd ../chat-service && npm install || true
          cd ../notification-service && npm install || true

      # 🔴 OWASP
      - name: OWASP Scan
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "chat-app"
          path: "."
          format: "HTML"

      # 🔴 SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Distributed-Chat-Application
            -Dsonar.organization=suryaparua-official
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 🟢 Docker login
      - name: Login DockerHub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # 🟢 Build Images with tag
      - name: Build Images
        run: |
          docker build -t $DOCKER_USERNAME/user-service:${IMAGE_TAG} ./backend/user-service
          docker build -t $DOCKER_USERNAME/chat-service:${IMAGE_TAG} ./backend/chat-service
          docker build -t $DOCKER_USERNAME/notification-service:${IMAGE_TAG} ./backend/notification-service
          docker build -t $DOCKER_USERNAME/nginx-gateway:${IMAGE_TAG} ./backend/nginx

      # 🔴 Trivy Scan
      - name: Trivy Scan User
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/user-service:${{ env.IMAGE_TAG }}

      - name: Trivy Scan Chat
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/chat-service:${{ env.IMAGE_TAG }}

      - name: Trivy Scan Notification
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/notification-service:${{ env.IMAGE_TAG }}

      # 🟢 Push
      - name: Push Images
        run: |
          docker push $DOCKER_USERNAME/user-service:${IMAGE_TAG}
          docker push $DOCKER_USERNAME/chat-service:${IMAGE_TAG}
          docker push $DOCKER_USERNAME/notification-service:${IMAGE_TAG}
          docker push $DOCKER_USERNAME/nginx-gateway:${IMAGE_TAG}
